CREATE DATABASE AXIS;
USE AXIS;

CREATE TABLE zones (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255),
    center_lat DECIMAL(10,7),
    center_lng DECIMAL(10,7),
    radius_meters INT,
    polygon JSON,
    risk_score INT DEFAULT 100,
    total_votes INT DEFAULT 0,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

SELECT * FROM ZONES;